/* Javascript output generated by archetype 1.2.15 */

/* Utils functions */

export const mk_int = (v) => {
  return { int: v.toString() };
};
export const mk_string = (v) => {
  return { string: v };
};
export const mk_bytes = (v) => {
  return { bytes: v.toString() };
};
export const mk_some = (v) => {
  return { prim: 'Some', args: [v] };
};
export const mk_none = () => {
  return { prim: 'None' };
};
export const mk_rational = (n, d) => {
  return { prim: 'Pair', args: [{ int: n.toString() }, { int: d.toString() }] };
};

/* Code */

export const code = [
  {
    prim: 'storage',
    args: [
      {
        prim: 'pair',
        args: [
          {
            prim: 'map',
            args: [
              { prim: 'int' },
              {
                prim: 'pair',
                args: [
                  { prim: 'string', annots: ['%desc'] },
                  { prim: 'int', annots: ['%nbvotes'] },
                ],
              },
            ],
            annots: ['%idea'],
          },
          {
            prim: 'pair',
            args: [
              {
                prim: 'map',
                args: [{ prim: 'address' }, { prim: 'int' }],
                annots: ['%voter'],
              },
              { prim: 'set', args: [{ prim: 'int' }], annots: ['%selected'] },
            ],
          },
        ],
      },
    ],
  },
  {
    prim: 'parameter',
    args: [
      {
        prim: 'or',
        args: [
          {
            prim: 'or',
            args: [
              { prim: 'address', annots: ['%register'] },
              { prim: 'string', annots: ['%add_idea'] },
            ],
          },
          {
            prim: 'or',
            args: [
              {
                prim: 'pair',
                args: [
                  { prim: 'int', annots: ['%n'] },
                  { prim: 'int', annots: ['%weight'] },
                ],
                annots: ['%vote'],
              },
              { prim: 'unit', annots: ['%finalize'] },
            ],
          },
        ],
      },
    ],
  },
  {
    prim: 'code',
    args: [
      [
        { prim: 'UNPAIR' },
        {
          prim: 'DIP',
          args: [{ int: '1' }, [{ prim: 'UNPAIR', args: [{ int: '3' }] }]],
        },
        {
          prim: 'IF_LEFT',
          args: [
            [
              {
                prim: 'IF_LEFT',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [
                        { prim: 'address' },
                        { string: 'tz1ZAQXACaEqryobpBoLbJUc2DjG5ZzrhARu' },
                      ],
                    },
                    { prim: 'SENDER' },
                    { prim: 'COMPARE' },
                    { prim: 'EQ' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCaller' },
                            ],
                          },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'DUP', args: [{ int: '2' }] },
                    { prim: 'MEM' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'voter' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'KeyExists' }],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [
                          { prim: 'DUP', args: [{ int: '3' }] },
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'int' }, { int: '5' }],
                          },
                          { prim: 'SOME' },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          { prim: 'UPDATE' },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '2' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '2' }] },
                        ],
                      ],
                    },
                    { prim: 'DROP', args: [{ int: '1' }] },
                    { prim: 'PAIR', args: [{ int: '3' }] },
                    { prim: 'NIL', args: [{ prim: 'operation' }] },
                    { prim: 'PAIR' },
                  ],
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'int' }, { int: '172800' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'timestamp' }, { int: '1595376000' }],
                    },
                    { prim: 'SUB' },
                    { prim: 'NOW' },
                    { prim: 'COMPARE' },
                    { prim: 'LE' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r0' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP', args: [{ int: '2' }] },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'SIZE' },
                    { prim: 'INT' },
                    { prim: 'MEM' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'idea' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'KeyExists' }],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [
                          { prim: 'DUP', args: [{ int: '2' }] },
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'int' }, { int: '0' }],
                          },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          { prim: 'PAIR' },
                          { prim: 'SOME' },
                          { prim: 'DUP', args: [{ int: '4' }] },
                          { prim: 'SIZE' },
                          { prim: 'INT' },
                          { prim: 'UPDATE' },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'DROP', args: [{ int: '1' }] },
                    { prim: 'PAIR', args: [{ int: '3' }] },
                    { prim: 'NIL', args: [{ prim: 'operation' }] },
                    { prim: 'PAIR' },
                  ],
                ],
              },
            ],
            [
              {
                prim: 'IF_LEFT',
                args: [
                  [
                    { prim: 'UNPAIR' },
                    { prim: 'SWAP' },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'SENDER' },
                    { prim: 'MEM' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r1' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'timestamp' }, { int: '1595376000' }],
                    },
                    { prim: 'NOW' },
                    { prim: 'COMPARE' },
                    { prim: 'LE' },
                    { prim: 'NOW' },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'int' }, { int: '172800' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'timestamp' }, { int: '1595376000' }],
                    },
                    { prim: 'SUB' },
                    { prim: 'COMPARE' },
                    { prim: 'LT' },
                    { prim: 'AND' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r2' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP' },
                    { prim: 'DUP', args: [{ int: '5' }] },
                    { prim: 'SENDER' },
                    { prim: 'GET' },
                    {
                      prim: 'IF_NONE',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'voter' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'AssetNotFound' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'COMPARE' },
                    { prim: 'GE' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r3' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'SENDER' },
                    { prim: 'GET' },
                    {
                      prim: 'IF_NONE',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'voter' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'AssetNotFound' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP', args: [{ int: '5' }] },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'SUB' },
                    { prim: 'SOME' },
                    { prim: 'SENDER' },
                    { prim: 'UPDATE' },
                    {
                      prim: 'DIP',
                      args: [
                        { int: '1' },
                        [
                          { prim: 'DIG', args: [{ int: '4' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'DUG', args: [{ int: '4' }] },
                    { prim: 'DROP', args: [{ int: '1' }] },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'DUP', args: [{ int: '3' }] },
                    { prim: 'GET' },
                    {
                      prim: 'IF_NONE',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'idea' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'AssetNotFound' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'DUP', args: [{ int: '5' }] },
                    { prim: 'DUP', args: [{ int: '5' }] },
                    { prim: 'GET' },
                    {
                      prim: 'IF_NONE',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'idea' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'AssetNotFound' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'UNPAIR' },
                    { prim: 'SWAP' },
                    { prim: 'DROP', args: [{ int: '1' }] },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'CDR' },
                    { prim: 'ADD' },
                    { prim: 'SWAP' },
                    { prim: 'PAIR' },
                    { prim: 'SOME' },
                    { prim: 'DUP', args: [{ int: '5' }] },
                    { prim: 'UPDATE' },
                    {
                      prim: 'DIP',
                      args: [
                        { int: '1' },
                        [
                          { prim: 'DIG', args: [{ int: '3' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'DUG', args: [{ int: '3' }] },
                    { prim: 'DROP', args: [{ int: '3' }] },
                    { prim: 'PAIR', args: [{ int: '3' }] },
                    { prim: 'NIL', args: [{ prim: 'operation' }] },
                    { prim: 'PAIR' },
                  ],
                  [
                    { prim: 'DROP', args: [{ int: '1' }] },
                    {
                      prim: 'PUSH',
                      args: [
                        { prim: 'address' },
                        { string: 'tz1ZAQXACaEqryobpBoLbJUc2DjG5ZzrhARu' },
                      ],
                    },
                    { prim: 'SENDER' },
                    { prim: 'COMPARE' },
                    { prim: 'EQ' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCaller' },
                            ],
                          },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'timestamp' }, { int: '1595376000' }],
                    },
                    { prim: 'NOW' },
                    { prim: 'COMPARE' },
                    { prim: 'GT' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r4' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'PUSH', args: [{ prim: 'nat' }, { int: '0' }] },
                    { prim: 'DUP', args: [{ int: '4' }] },
                    { prim: 'SIZE' },
                    { prim: 'COMPARE' },
                    { prim: 'EQ' },
                    { prim: 'NOT' },
                    {
                      prim: 'IF',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'string' }, { string: 'r5' }],
                          },
                          {
                            prim: 'PUSH',
                            args: [
                              { prim: 'string' },
                              { string: 'InvalidCondition' },
                            ],
                          },
                          { prim: 'PAIR' },
                          { prim: 'FAILWITH' },
                        ],
                        [],
                      ],
                    },
                    { prim: 'NIL', args: [{ prim: 'int' }] },
                    { prim: 'NIL', args: [{ prim: 'int' }] },
                    { prim: 'PUSH', args: [{ prim: 'nat' }, { int: '0' }] },
                    { prim: 'PAIR' },
                    { prim: 'NIL', args: [{ prim: 'int' }] },
                    { prim: 'NIL', args: [{ prim: 'int' }] },
                    { prim: 'NIL', args: [{ prim: 'int' }] },
                    { prim: 'DUP', args: [{ int: '6' }] },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          { prim: 'UNPAIR' },
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'int' }, { int: '5' }],
                          },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          { prim: 'CDR' },
                          { prim: 'COMPARE' },
                          { prim: 'GE' },
                          {
                            prim: 'IF',
                            args: [
                              [
                                { prim: 'DUP', args: [{ int: '3' }] },
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CONS' },
                              ],
                              [{ prim: 'DUP', args: [{ int: '3' }] }],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '2' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '2' }] },
                          { prim: 'DROP', args: [{ int: '2' }] },
                        ],
                      ],
                    },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'CONS' },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '1' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          { prim: 'DUP', args: [{ int: '5' }] },
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'GET' },
                          {
                            prim: 'IF_NONE',
                            args: [
                              [
                                {
                                  prim: 'PUSH',
                                  args: [
                                    { prim: 'string' },
                                    { string: 'idea' },
                                  ],
                                },
                                {
                                  prim: 'PUSH',
                                  args: [
                                    { prim: 'string' },
                                    { string: 'AssetNotFound' },
                                  ],
                                },
                                { prim: 'PAIR' },
                                { prim: 'FAILWITH' },
                              ],
                              [],
                            ],
                          },
                          { prim: 'NIL', args: [{ prim: 'int' }] },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          { prim: 'SOME' },
                          { prim: 'PAIR' },
                          { prim: 'DUP', args: [{ int: '4' }] },
                          {
                            prim: 'ITER',
                            args: [
                              [
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CAR' },
                                { prim: 'DUP', args: [{ int: '3' }] },
                                { prim: 'CDR' },
                                { prim: 'DUP', args: [{ int: '2' }] },
                                {
                                  prim: 'IF_NONE',
                                  args: [
                                    [
                                      { prim: 'DUP' },
                                      { prim: 'DUP', args: [{ int: '4' }] },
                                      { prim: 'CONS' },
                                      { prim: 'DUP', args: [{ int: '3' }] },
                                      { prim: 'PAIR' },
                                    ],
                                    [
                                      {
                                        prim: 'PUSH',
                                        args: [{ prim: 'int' }, { int: '0' }],
                                      },
                                      { prim: 'DUP', args: [{ int: '12' }] },
                                      { prim: 'DUP', args: [{ int: '6' }] },
                                      { prim: 'GET' },
                                      {
                                        prim: 'IF_NONE',
                                        args: [
                                          [
                                            {
                                              prim: 'PUSH',
                                              args: [
                                                { prim: 'string' },
                                                { string: 'idea' },
                                              ],
                                            },
                                            {
                                              prim: 'PUSH',
                                              args: [
                                                { prim: 'string' },
                                                { string: 'AssetNotFound' },
                                              ],
                                            },
                                            { prim: 'PAIR' },
                                            { prim: 'FAILWITH' },
                                          ],
                                          [],
                                        ],
                                      },
                                      { prim: 'DUP', args: [{ int: '8' }] },
                                      { prim: 'CDR' },
                                      { prim: 'DUP', args: [{ int: '2' }] },
                                      { prim: 'CDR' },
                                      { prim: 'COMPARE' },
                                      { prim: 'LT' },
                                      {
                                        prim: 'IF',
                                        args: [
                                          [
                                            {
                                              prim: 'PUSH',
                                              args: [
                                                { prim: 'int' },
                                                { int: '1' },
                                              ],
                                            },
                                          ],
                                          [
                                            {
                                              prim: 'PUSH',
                                              args: [
                                                { prim: 'int' },
                                                { int: '0' },
                                              ],
                                            },
                                          ],
                                        ],
                                      },
                                      {
                                        prim: 'DIP',
                                        args: [
                                          { int: '1' },
                                          [
                                            {
                                              prim: 'DROP',
                                              args: [{ int: '1' }],
                                            },
                                          ],
                                        ],
                                      },
                                      { prim: 'COMPARE' },
                                      { prim: 'GT' },
                                      {
                                        prim: 'IF',
                                        args: [
                                          [
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '2' }],
                                            },
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '8' }],
                                            },
                                            { prim: 'CONS' },
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '5' }],
                                            },
                                            { prim: 'CONS' },
                                            {
                                              prim: 'NONE',
                                              args: [{ prim: 'int' }],
                                            },
                                            { prim: 'PAIR' },
                                          ],
                                          [
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '2' }],
                                            },
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '5' }],
                                            },
                                            { prim: 'CONS' },
                                            {
                                              prim: 'DUP',
                                              args: [{ int: '4' }],
                                            },
                                            { prim: 'PAIR' },
                                          ],
                                        ],
                                      },
                                      { prim: 'SWAP' },
                                      { prim: 'DROP', args: [{ int: '1' }] },
                                    ],
                                  ],
                                },
                                {
                                  prim: 'DIP',
                                  args: [
                                    { int: '1' },
                                    [{ prim: 'DROP', args: [{ int: '1' }] }],
                                  ],
                                },
                                {
                                  prim: 'DIP',
                                  args: [
                                    { int: '1' },
                                    [{ prim: 'DROP', args: [{ int: '1' }] }],
                                  ],
                                },
                                {
                                  prim: 'DIP',
                                  args: [
                                    { int: '1' },
                                    [
                                      { prim: 'DIG', args: [{ int: '1' }] },
                                      { prim: 'DROP', args: [{ int: '1' }] },
                                    ],
                                  ],
                                },
                                { prim: 'DUG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUP' },
                          { prim: 'CAR' },
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'CDR' },
                          { prim: 'NIL', args: [{ prim: 'int' }] },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          {
                            prim: 'IF_NONE',
                            args: [
                              [{ prim: 'DUP', args: [{ int: '2' }] }],
                              [
                                { prim: 'DUP', args: [{ int: '3' }] },
                                { prim: 'DUP', args: [{ int: '8' }] },
                                { prim: 'CONS' },
                                { prim: 'SWAP' },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          {
                            prim: 'ITER',
                            args: [
                              [
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CONS' },
                                {
                                  prim: 'DIP',
                                  args: [
                                    { int: '1' },
                                    [
                                      { prim: 'DIG', args: [{ int: '1' }] },
                                      { prim: 'DROP', args: [{ int: '1' }] },
                                    ],
                                  ],
                                },
                                { prim: 'DUG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [{ prim: 'DROP', args: [{ int: '1' }] }],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [{ prim: 'DROP', args: [{ int: '1' }] }],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [{ prim: 'DROP', args: [{ int: '1' }] }],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [{ prim: 'DROP', args: [{ int: '1' }] }],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '1' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          {
                            prim: 'PUSH',
                            args: [{ prim: 'nat' }, { int: '3' }],
                          },
                          { prim: 'DUP', args: [{ int: '3' }] },
                          { prim: 'CAR' },
                          { prim: 'COMPARE' },
                          { prim: 'LT' },
                          {
                            prim: 'IF',
                            args: [
                              [
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CDR' },
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CONS' },
                                {
                                  prim: 'PUSH',
                                  args: [{ prim: 'nat' }, { int: '1' }],
                                },
                                { prim: 'DUP', args: [{ int: '4' }] },
                                { prim: 'CAR' },
                                { prim: 'ADD' },
                                { prim: 'PAIR' },
                              ],
                              [
                                { prim: 'DUP', args: [{ int: '2' }] },
                                { prim: 'CDR' },
                                {
                                  prim: 'PUSH',
                                  args: [{ prim: 'nat' }, { int: '1' }],
                                },
                                { prim: 'DUP', args: [{ int: '4' }] },
                                { prim: 'CAR' },
                                { prim: 'ADD' },
                                { prim: 'PAIR' },
                              ],
                            ],
                          },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '1' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'CDR' },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'CONS' },
                          {
                            prim: 'DIP',
                            args: [
                              { int: '1' },
                              [
                                { prim: 'DIG', args: [{ int: '1' }] },
                                { prim: 'DROP', args: [{ int: '1' }] },
                              ],
                            ],
                          },
                          { prim: 'DUG', args: [{ int: '1' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    {
                      prim: 'ITER',
                      args: [
                        [
                          { prim: 'DUP', args: [{ int: '4' }] },
                          { prim: 'DUP', args: [{ int: '2' }] },
                          { prim: 'MEM' },
                          {
                            prim: 'IF',
                            args: [
                              [
                                {
                                  prim: 'PUSH',
                                  args: [
                                    { prim: 'string' },
                                    { string: 'selected' },
                                  ],
                                },
                                {
                                  prim: 'PUSH',
                                  args: [
                                    { prim: 'string' },
                                    { string: 'KeyExists' },
                                  ],
                                },
                                { prim: 'PAIR' },
                                { prim: 'FAILWITH' },
                              ],
                              [
                                { prim: 'DUP', args: [{ int: '4' }] },
                                {
                                  prim: 'PUSH',
                                  args: [{ prim: 'bool' }, { prim: 'True' }],
                                },
                                { prim: 'DUP', args: [{ int: '3' }] },
                                { prim: 'UPDATE' },
                                {
                                  prim: 'DIP',
                                  args: [
                                    { int: '1' },
                                    [
                                      { prim: 'DIG', args: [{ int: '3' }] },
                                      { prim: 'DROP', args: [{ int: '1' }] },
                                    ],
                                  ],
                                },
                                { prim: 'DUG', args: [{ int: '3' }] },
                              ],
                            ],
                          },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'PAIR', args: [{ int: '3' }] },
                    { prim: 'NIL', args: [{ prim: 'operation' }] },
                    { prim: 'PAIR' },
                  ],
                ],
              },
            ],
          ],
        },
      ],
    ],
  },
];

export const getStorage = () => {
  return { prim: 'Pair', args: [[], { prim: 'Pair', args: [[], []] }] };
};
