/* Javascript output generated by archetype 1.2.15 */

/* Utils functions */

export const mk_int    = v  => {return { "int" : v.toString() }}
export const mk_string = v  => {return { "string" : v }}
export const mk_bytes  = v  => {return { "bytes" : v.toString() }}
export const mk_some   = v  => {return { "prim": "Some", "args": [ v ] }}
export const mk_none   = () => {return { "prim": "None" }}
export const mk_rational = (n, d) => {return {  "prim": "Pair", "args": [ {  "int": n.toString()  }, {  "int": d.toString()  } ] }}

/* Code */

export const code =
  [  {  "prim": "storage",
        "args": [
          {  "prim": "unit"  }
        ]
  },
  {  "prim": "parameter",
     "args": [
       {  "prim": "unit",
          "annots": [
            "%myaction"
          ]
       }
     ]
  },
  {  "prim": "code",
     "args": [
       [  {  "prim": "UNPAIR"  },
       {  "prim": "DROP",
          "args": [
            {  "int": "1"  }
          ]
       },
       {  "prim": "NIL",
          "args": [
            {  "prim": "operation"  }
          ]
       },
       {  "prim": "PAIR"  }  ]
     ]
  }  ];

export const getStorage = () => {
  return {  "prim": "Unit"  };
  }
