/* Javascript output generated by archetype 1.2.15 */

/* Utils functions */

export const mk_int = (v) => {
  return { int: v.toString() };
};
export const mk_string = (v) => {
  return { string: v };
};
export const mk_bytes = (v) => {
  return { bytes: v.toString() };
};
export const mk_some = (v) => {
  return { prim: 'Some', args: [v] };
};
export const mk_none = () => {
  return { prim: 'None' };
};
export const mk_rational = (n, d) => {
  return { prim: 'Pair', args: [{ int: n.toString() }, { int: d.toString() }] };
};

/* Code */

export const code = [
  {
    prim: 'storage',
    args: [
      {
        prim: 'pair',
        args: [
          { prim: 'mutez', annots: ['%max_bid'] },
          {
            prim: 'pair',
            args: [
              {
                prim: 'map',
                args: [{ prim: 'address' }, { prim: 'mutez' }],
                annots: ['%bid'],
              },
              { prim: 'timestamp', annots: ['%deadline'] },
            ],
          },
        ],
      },
    ],
  },
  {
    prim: 'parameter',
    args: [
      {
        prim: 'or',
        args: [
          { prim: 'unit', annots: ['%place_bid'] },
          { prim: 'unit', annots: ['%reclaim'] },
        ],
      },
    ],
  },
  {
    prim: 'code',
    args: [
      [
        { prim: 'NIL', args: [{ prim: 'operation' }] },
        { prim: 'DIG', args: [{ int: '1' }] },
        { prim: 'UNPAIR' },
        {
          prim: 'DIP',
          args: [{ int: '1' }, [{ prim: 'UNPAIR', args: [{ int: '3' }] }]],
        },
        {
          prim: 'IF_LEFT',
          args: [
            [
              { prim: 'DROP', args: [{ int: '1' }] },
              { prim: 'DUP', args: [{ int: '3' }] },
              { prim: 'NOW' },
              { prim: 'COMPARE' },
              { prim: 'LT' },
              { prim: 'NOT' },
              {
                prim: 'IF',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'c1' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [
                        { prim: 'string' },
                        { string: 'InvalidCondition' },
                      ],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'DUP', args: [{ int: '2' }] },
              { prim: 'SENDER' },
              { prim: 'MEM' },
              {
                prim: 'IF',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'bid' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'KeyExists' }],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [
                    { prim: 'DUP', args: [{ int: '2' }] },
                    { prim: 'AMOUNT' },
                    { prim: 'SOME' },
                    { prim: 'SENDER' },
                    { prim: 'UPDATE' },
                    {
                      prim: 'DIP',
                      args: [
                        { int: '1' },
                        [
                          { prim: 'DIG', args: [{ int: '1' }] },
                          { prim: 'DROP', args: [{ int: '1' }] },
                        ],
                      ],
                    },
                    { prim: 'DUG', args: [{ int: '1' }] },
                  ],
                ],
              },
              { prim: 'DUP' },
              { prim: 'AMOUNT' },
              { prim: 'PAIR' },
              { prim: 'DUP' },
              { prim: 'UNPAIR' },
              { prim: 'COMPARE' },
              { prim: 'LT' },
              { prim: 'IF', args: [[{ prim: 'CDR' }], [{ prim: 'CAR' }]] },
              { prim: 'SWAP' },
              { prim: 'DROP', args: [{ int: '1' }] },
              { prim: 'PAIR', args: [{ int: '3' }] },
              { prim: 'DIG', args: [{ int: '1' }] },
              { prim: 'PAIR' },
            ],
            [
              { prim: 'DROP', args: [{ int: '1' }] },
              { prim: 'DUP', args: [{ int: '3' }] },
              { prim: 'NOW' },
              { prim: 'COMPARE' },
              { prim: 'LT' },
              { prim: 'NOT' },
              {
                prim: 'IF',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'c2' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [
                        { prim: 'string' },
                        { string: 'InvalidCondition' },
                      ],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'DUP' },
              { prim: 'DUP', args: [{ int: '3' }] },
              { prim: 'SENDER' },
              { prim: 'GET' },
              {
                prim: 'IF_NONE',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'bid' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'AssetNotFound' }],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'COMPARE' },
              { prim: 'LT' },
              { prim: 'NOT' },
              {
                prim: 'IF',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'c3' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [
                        { prim: 'string' },
                        { string: 'InvalidCondition' },
                      ],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'NIL', args: [{ prim: 'operation' }] },
              { prim: 'NIL', args: [{ prim: 'operation' }] },
              { prim: 'DUP', args: [{ int: '6' }] },
              { prim: 'ITER', args: [[{ prim: 'CONS' }]] },
              { prim: 'SENDER' },
              { prim: 'CONTRACT', args: [{ prim: 'unit' }] },
              {
                prim: 'IF_NONE',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'EntryNotFound' }],
                    },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'DUP', args: [{ int: '5' }] },
              { prim: 'SENDER' },
              { prim: 'GET' },
              {
                prim: 'IF_NONE',
                args: [
                  [
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'bid' }],
                    },
                    {
                      prim: 'PUSH',
                      args: [{ prim: 'string' }, { string: 'AssetNotFound' }],
                    },
                    { prim: 'PAIR' },
                    { prim: 'FAILWITH' },
                  ],
                  [],
                ],
              },
              { prim: 'UNIT' },
              { prim: 'TRANSFER_TOKENS' },
              { prim: 'CONS' },
              { prim: 'ITER', args: [[{ prim: 'CONS' }]] },
              {
                prim: 'DIP',
                args: [
                  { int: '1' },
                  [
                    { prim: 'DIG', args: [{ int: '3' }] },
                    { prim: 'DROP', args: [{ int: '1' }] },
                  ],
                ],
              },
              { prim: 'DUG', args: [{ int: '3' }] },
              { prim: 'PAIR', args: [{ int: '3' }] },
              { prim: 'DIG', args: [{ int: '1' }] },
              { prim: 'PAIR' },
            ],
          ],
        },
      ],
    ],
  },
];

export const getStorage = () => {
  return {
    prim: 'Pair',
    args: [{ int: '0' }, { prim: 'Pair', args: [[], { int: '1546300800' }] }],
  };
};
