name: Mocha Contract Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: setup project
      run: npm ci
    - name: Install mocha
      run: npm install -g mocha
    - name: Install completium
      run: npm i @completium/completium-cli@0.3.19 -g
    - name: setup completium
      run: completium-cli init
    - name: 'set tezos endpoint'
      run: completium-cli set endpoint https://kathmandunet.ecadinfra.com
    - name: 'generate bob account'
      run: completium-cli generate account as bob
    - name: 'generate carl account'
      run: completium-cli generate account as carl
    - name: 'generate daniel account'
      run: completium-cli generate account as daniel
    - name: run mocha tests
      run: npm run mochaCI